### ISSUE TITLE
Practica 1. Planificación de recursos

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-mitte#1]
[Practica 1 Planificacion de recursos.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-mitte/files/7555693/Practica.1.Planificacion.de.recursos.pdf)

**Comment by garaudy12** [comment]
Calificacion:20% 
El trabajo cumplió con los objetivos esperados, tiene buena argumentación y todo se ve claramente.

**Comment by Jaci14** [comment]
Cumple con el objetivo de la practica, el EDT es entendible y realiza un buen cronograma de actividades para maximizar la eficiencia de las actividades.

Calificación: 20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
