### ISSUE TITLE
Practica 2. Gestión de riesgos 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-mitte#2]
[Practica 2 gestion de riesgod.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-mitte/files/7557245/Practica.2.gestion.de.riesgod.pdf)
)

**Comment by 10154** [comment]
Esta práctica cumple con todos los requisitos, esta bien estructurada y cuenta con todos los puntos,  obtuvo un porcentaje de 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado
